# Generated by Django 5.0.1 on 2024-01-27 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0003_group_user_note_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='user',
        ),
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
    ]
